routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('/program', 'MenuController@program')
    ->name('program');
Route::get('/faq', 'MenuController@faq')
    ->name('faq');
Route::get('/galeri', 'MenuController@galeri')
    ->name('galeri');
Route::get('/download', 'MenuController@download')
    ->name('download');

Route::get('/agent', 'HomeController@agent');

Route::get('/register/agen', 'Auth\RegisterController@showAgenRegisterForm')
    ->name('register.agen');

Route::post('/register/prosess', 'Auth\RegisterController@prosess')
    ->name('register.prosess');

Route::get('/detail/{slug}', 'DetailController@index')
    ->name('detail');

// user login
Route::post('/checkout/{id}', 'CheckoutController@process')
    ->name('checkout_process');
// ->middleware(['auth', 'verified']);

Route::get('/checkout/{id}', 'CheckoutController@index')
    ->name('checkout');
// ->middleware(['auth', 'verified']);

Route::post('/checkout/create/{detail_id}', 'CheckoutController@create')
    ->name('checkout-create');
// ->middleware(['auth', 'verified']);

Route::get('/checkout/remove/{detail_id}', 'CheckoutController@remove')
    ->name('checkout-remove');
// ->middleware(['auth', 'verified']);

Route::post('/send-wa', 'CheckoutController@sendWhatsapp');

Route::get('/checkout/confirm/{id}', 'CheckoutController@success')
    ->name('checkout-success');
// ->middleware(['auth', 'verified']);

Route::group(['middleware' => 'auth', 'verified'], function () {

    Route::get('/profile', 'ProfileController@edit')
        ->name('profile.edit')
        ->middleware(['auth', 'verified']);

    Route::patch('/profile', 'ProfileController@update')
        ->name('profile.update')->middleware(['auth', 'verified']);

    Route::get('/pengaturan-bank', 'PengaturanBankController@edit')
        ->name('pengaturan-bank.edit')->middleware(['auth', 'verified']);

    Route::patch('/pengaturan-bank', 'PengaturanBankController@update')
        ->name('pengaturan-bank.update')->middleware(['auth', 'verified']);

    Route::get('/document', 'DocumentController@edit')
        ->name('document.edit')->middleware(['auth', 'verified']);

    Route::patch('/document', 'DocumentController@update')
        ->name('document.update')->middleware(['auth', 'verified']);

    Route::get('password', 'PasswordController@edit')
        ->name('user.password.edit')->middleware(['auth', 'verified']);

    Route::patch('password', 'PasswordController@update')
        ->name('user.password.update')->middleware(['auth', 'verified']);

    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index')->middleware(['auth', 'verified']);
    Route::resource('transaction', 'TransactionController')->middleware(['auth', 'verified']);
    // Route::get('transaction', 'TransactionController@index')
    //     ->name('transaction.index')->middleware(['auth', 'verified']);
    Route::get('dompet', 'DompetController@index')
        ->name('dompet.index')->middleware(['auth', 'verified']);
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

//agratek
Route::post('/agratek/callback', 'InvoiceController@agratekCallback');

// admin
Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('banks', 'BanksController');
        Route::resource('role', 'RoleController');
        Route::resource('product', 'ProductController');
        Route::resource('gallery', 'GalleryController');

        Route::resource(
            'addtransaksi',
            'AddtransaksiController',
            ['except' => [
                'show', 'update', 'index', 'destroy ',
                'edit'
            ]]
        );
    });

Auth::routes(['verify' => true]);

// midtrans
// Route::post('/midtrans/callback', 'MidtransController@notificationHandler');
Route::get('/invoice/{id}', 'InvoiceController@finishRedirect')
    ->name('invoice');
// Route::get('/midtrans/unfinish', 'MidtransController@unfinishRedirect');
// Route::get('/midtrans/error', 'MidtransController@errorRedirect');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Gallery extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'product_id', 'image'
    ];

    protected $hidden = [];

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }
}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\GalleryRequest;
use App\Gallery;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Gallery::with(['product'])->get();

        return view('pages.admin.gallery.index', [
            'items' => $items,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = Product::all();
        return view('pages.admin.gallery.create', [
            'product' => $product
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = $request->file('image');

        Gallery::create([
            'product_id' => $request->product_id,
            'image' => $image->getClientOriginalName()
        ]);
        $image->storeAs('public/gallery_hewan', $image->getClientOriginalName());

        session()->flash('sukses', 'Galleri berhasil di Tambah');
        return redirect()->route('gallery.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Gallery::findOrFail($id);
        $product = Product::all();

        return view('pages.admin.gallery.edit', [
            'item' => $item,
            'product' => $product
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(GalleryRequest $request, Gallery $gallery)
    {
        $image = $request->file('fotobuku');

        $gallery = Gallery::whereId($gallery->id)->update([
            'product_id' => $request->input('product_id'),
            'image' => $image->getClientOriginalName()
        ]);

        $image->storeAs('public/gallery_hewan', $image->getClientOriginalName());


        session()->flash('sukses', 'Galleri berhasil di Ubah');
        return redirect()->route('gallery.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Gallery::findorFail($id);
        $item->delete();

        return redirect()->route('gallery.index');
    }
}

resources/views/pages/admin/gallery/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">
        <!-- Content Row -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="row mt-12">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="col-xl-12 col-md-8 mb-5">
                        <div class="card border-left-warning shadow h-100 py-2">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="modal-body">
                                        <h3 class="h3 mb-4 text-gray-800">
                                            Tambah Gallery
                                        </h3>
                                        <hr>
                                        <form action="{{ route('gallery.store') }}" method="post"
                                            enctype="multipart/form-data">
                                            @csrf
                                            <div class="form-group">
                                                <label for="title">Product</label>
                                                <select name="product_id" required class="form-control">
                                                    <option disabled selected>Pilih Product</option>
                                                    @foreach ($product as $item)
                                                        <option value="{{ $item->id }}">
                                                            {{ $item->title }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="image">Image</label>
                                                <input type="file" class="form-control" name="image" placeholder="Image">
                                            </div>
                                            <button type="submit" class="btn admin-login btn-user btn-block admin-btn">
                                                Simpan
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/gallery/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Ubah Gallery</h1>
        </div>

        <!-- Content Row -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="card shadow">
            <div class="card-body">
                <form action="{{ route('gallery.update', $item->id) }}" method="post" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="title">Tipe Hewan Qurban</label>
                        <select name="product_id" required class="form-control">
                            <option value="{{ $item->product_id }}">Jangan Ubah</option>
                            @foreach ($product as $items)
                                <option value="{{ $items->id }}">
                                    {{ $items->title }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" class="form-control" name="image" placeholder="Image">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">
                        Ubah
                    </button>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/gallery/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Gallery</h1>
            <a href="{{ route('gallery.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Gallery
            </a>
        </div>

        <!-- Content Row -->
        <div class="row">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Tipe Hewan</th>
                                <th>Gambar</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @forelse($items as $item)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $item->product->title }}</td>
                                    <td>
                                        <img src="{{ Storage::url('public/gallery_hewan/' . $item->image) }}" alt=""
                                            style="width: 200px" class="img-thumbnail">
                                    </td>
                                    <td>
                                        <a href="{{ route('gallery.edit', $item->id) }}" class="btn btn-info">
                                            <i class="fa fa-pencil-alt"></i>
                                        </a>
                                        <form action="{{ route('gallery.destroy', $item->id) }}" method="post" class="d-inline">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>

                                    </td>
                                </tr>
                            @empty
                                <td colspan="7" class="text-center">
                                    Data Kosong
                                </td>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection