routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('/program', 'MenuController@program')
    ->name('program');
Route::get('/faq', 'MenuController@faq')
    ->name('faq');
Route::get('/galeri', 'MenuController@galeri')
    ->name('galeri');
Route::get('/download', 'MenuController@download')
    ->name('download');

Route::get('/agent', 'HomeController@agent');

Route::get('/register/agen', 'Auth\RegisterController@showAgenRegisterForm')
    ->name('register.agen');

Route::post('/register/prosess', 'Auth\RegisterController@prosess')
    ->name('register.prosess');

Route::get('/detail/{slug}', 'DetailController@index')
    ->name('detail');

// user login
Route::post('/checkout/{id}', 'CheckoutController@process')
    ->name('checkout_process');
// ->middleware(['auth', 'verified']);

Route::get('/checkout/{id}', 'CheckoutController@index')
    ->name('checkout');
// ->middleware(['auth', 'verified']);

Route::post('/checkout/create/{detail_id}', 'CheckoutController@create')
    ->name('checkout-create');
// ->middleware(['auth', 'verified']);

Route::get('/checkout/remove/{detail_id}', 'CheckoutController@remove')
    ->name('checkout-remove');
// ->middleware(['auth', 'verified']);

Route::post('/send-wa', 'CheckoutController@sendWhatsapp');

Route::get('/checkout/confirm/{id}', 'CheckoutController@success')
    ->name('checkout-success');
// ->middleware(['auth', 'verified']);

Route::group(['middleware' => 'auth', 'verified'], function () {

    Route::get('/profile', 'ProfileController@edit')
        ->name('profile.edit')
        ->middleware(['auth', 'verified']);

    Route::patch('/profile', 'ProfileController@update')
        ->name('profile.update')->middleware(['auth', 'verified']);

    Route::get('/pengaturan-bank', 'PengaturanBankController@edit')
        ->name('pengaturan-bank.edit')->middleware(['auth', 'verified']);

    Route::patch('/pengaturan-bank', 'PengaturanBankController@update')
        ->name('pengaturan-bank.update')->middleware(['auth', 'verified']);

    Route::get('/document', 'DocumentController@edit')
        ->name('document.edit')->middleware(['auth', 'verified']);

    Route::patch('/document', 'DocumentController@update')
        ->name('document.update')->middleware(['auth', 'verified']);

    Route::get('password', 'PasswordController@edit')
        ->name('user.password.edit')->middleware(['auth', 'verified']);

    Route::patch('password', 'PasswordController@update')
        ->name('user.password.update')->middleware(['auth', 'verified']);

    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index')->middleware(['auth', 'verified']);
    Route::resource('transaction', 'TransactionController')->middleware(['auth', 'verified']);
    // Route::get('transaction', 'TransactionController@index')
    //     ->name('transaction.index')->middleware(['auth', 'verified']);
    Route::get('dompet', 'DompetController@index')
        ->name('dompet.index')->middleware(['auth', 'verified']);
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

//agratek
Route::post('/agratek/callback', 'InvoiceController@agratekCallback');

// admin
Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('banks', 'BanksController');
        Route::resource('role', 'RoleController');
        Route::resource('product', 'ProductController');
        Route::resource('gallery', 'GalleryController');

        Route::resource(
            'addtransaksi',
            'AddtransaksiController',
            ['except' => [
                'show', 'update', 'index', 'destroy ',
                'edit'
            ]]
        );
    });

Auth::routes(['verify' => true]);

// midtrans
// Route::post('/midtrans/callback', 'MidtransController@notificationHandler');
Route::get('/invoice/{id}', 'InvoiceController@finishRedirect')
    ->name('invoice');
// Route::get('/midtrans/unfinish', 'MidtransController@unfinishRedirect');
// Route::get('/midtrans/error', 'MidtransController@errorRedirect');

resources/views/includes/admin/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Zakat Sukses <?= date('Y') ?></span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

resources/views/includes/admin/navbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                    {{ Auth::user()->username }}
                </span>
                <img class="img-profile rounded-circle"
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/OOjs_UI_icon_userAvatar.svg/1200px-OOjs_UI_icon_userAvatar.svg.png">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                @can('manage-users')
                    <a class="dropdown-item" href="{{ route('users.index') }}">
                        <i class="fas fa-users fa-sm fa-fw mr-2 text-gray-400"></i>
                        User Management
                    </a>
                @endcan
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Keluar
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

resources/views/includes/admin/script.blade.php
 <script src="vendor/jquery/jquery.min.js"></script>
 <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

 <!-- Core plugin JavaScript-->
 <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

 <!-- Custom scripts for all pages-->
 <script src="js/sb-admin-2.min.js"></script>

 <!-- Page level plugins -->
 <script src="vendor/datatables/jquery.dataTables.min.js"></script>
 <script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

 <!-- Page level custom scripts -->
 <script src="js/demo/datatables-demo.js"></script>

 <script src="{{ url('backend/vendor/jquery/jquery.min.js') }}"></script>
 <script src="{{ url('backend/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
 <script src="{{ url('backend/vendor/jquery-easing/jquery.easing.min.js') }}"></script>
 <script src="{{ url('backend/js/sb-admin-2.min.js') }}"></script>

 <script src="{{ url('backend/vendor/datatables/jquery.dataTables.min.js') }}"></script>
 <script src="{{ url('backend/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
 <script src="{{ url('backend/js/demo/datatables-demo.js') }}"></script>


 {{-- <script src="{{ url('backend/vendor/chart.js/Chart.min.js') }}"></script> --}}

 <!-- Page level custom scripts -->
 <script src="{{ url('backend/js/demo/chart-area-demo.js') }}"></script>
 <script src="{{ url('backend/js/demo/chart-pie-demo.js') }}"></script>
 <script src="{{ url('backend/js/demo/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>



 <script>
     $(function() {
         $('#only-number').on('keydown', '#nohp', function(e) {
             -1 !== $
                 .inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) || /65|67|86|88/
                 .test(e.keyCode) && (!0 === e.ctrlKey || !0 === e.metaKey) ||
                 35 <= e.keyCode && 40 >= e.keyCode || (e.shiftKey || 48 > e.keyCode || 57 < e
                     .keyCode) &&
                 (96 > e.keyCode || 105 < e.keyCode) && e.preventDefault()
         });
     });

     $(document).ready(function() {
         $("#show_hide_password a").on('click', function(event) {
             event.preventDefault();
             if ($('#show_hide_password input').attr("type") == "text") {
                 $('#show_hide_password input').attr('type', 'password');
                 $('#show_hide_password i').addClass("fa-eye-slash");
                 $('#show_hide_password i').removeClass("fa-eye");
             } else if ($('#show_hide_password input').attr("type") == "password") {
                 $('#show_hide_password input').attr('type', 'text');
                 $('#show_hide_password i').removeClass("fa-eye-slash");
                 $('#show_hide_password i').addClass("fa-eye");
             }
         });
     });

     $(document).ready(function() {
         $("#show_hide_passwordd a").on('click', function(event) {
             event.preventDefault();
             if ($('#show_hide_passwordd input').attr("type") == "text") {
                 $('#show_hide_passwordd input').attr('type', 'password');
                 $('#show_hide_passwordd i').addClass("fa-eye-slash");
                 $('#show_hide_passwordd i').removeClass("fa-eye");
             } else if ($('#show_hide_passwordd input').attr("type") == "password") {
                 $('#show_hide_passwordd input').attr('type', 'text');
                 $('#show_hide_passwordd i').removeClass("fa-eye-slash");
                 $('#show_hide_passwordd i').addClass("fa-eye");
             }
         });
     });

     $(document).ready(function() {
         $("#show_hide_password_login a").on('click', function(event) {
             event.preventDefault();
             if ($('#show_hide_password_login input').attr("type") == "text") {
                 $('#show_hide_password_login input').attr('type', 'password');
                 $('#show_hide_password_login i').addClass("fa-eye-slash");
                 $('#show_hide_password_login i').removeClass("fa-eye");
             } else if ($('#show_hide_password_login input').attr("type") == "password") {
                 $('#show_hide_password_login input').attr('type', 'text');
                 $('#show_hide_password_login i').removeClass("fa-eye-slash");
                 $('#show_hide_password_login i').addClass("fa-eye");
             }
         });
     });

 </script>

 <script>
     $(document).ready(function() {
         $('.datepicker').datepicker({
             format: 'dd-mm-yyyy',
             autoclose: true,
             todayHighlight: true,
         });
     });

 </script>

resources/views/includes/admin/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-dark sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('home') }}">
        <div class="sidebar-brand-text mx-3">
            ZAKAT SUKSES
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    @if (Auth::user()->role_id == 1)
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('dashboard.index') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <hr class="sidebar-divider">

        {{-- <li class="nav-item">
            <a class="nav-link" href="{{ route('dompet.index') }}">
                <i class="fas fa-fw fa-credit-card"></i>
                <span>Dompet</span></a>
        </li> --}}

        <li class="nav-item">
            <a class="nav-link" href="{{ route('transaction.index') }}">
                <i class="fas fa-fw fa-edit"></i>
                <span>Data Transaksi Qurban</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('document.edit') }}">
                <i class="fas fa-fw fa-id-card"></i>
                <span>Kelengkapan Document</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('pengaturan-bank.edit') }}">
                <i class="fas fa-fw fa-cogs"></i>
                <span>Pengaturan Bank</span></a>
        </li>

        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Admin
        </div>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('addtransaksi.create') }}">
                <i class="fas fa-fw fa-edit"></i>
                <span>Tambah Transaksi</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-edit"></i>
                <span>Product</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Product :</h6>
                    <a class="collapse-item" href="{{ route('product.index') }}">Product</a>
                    <a class="collapse-item" href="{{ route('gallery.index') }}">Gallery</a>
                </div>
            </div>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('role.index') }}">
                <i class=" fas fa-fw fa-user"></i>
                <span>Role</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('banks.index') }}">
                <i class="fas fa-fw fa-id-card"></i>
                <span>Banks</span></a>
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('users.index') }}">
                <i class="fas fa-fw fa-users"></i>
                <span>Users</span></a>
        </li>
    @elseif (Auth::user()->role_id == 2)
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('dashboard.index') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <hr class="sidebar-divider">
        <li class="nav-item">
            <a class="nav-link" href="{{ route('transaction.index') }}">
                <i class="fas fa-fw fa-edit"></i>
                <span>Data Transaksi Qurban</span></a>
        </li>
    @elseif (Auth::user()->role_id == 3)
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('dashboard.index') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <hr class="sidebar-divider">

        <li class="nav-item">
            <a class="nav-link" href="{{ route('dompet.index') }}">
                <i class="fas fa-fw fa-credit-card"></i>
                <span>Dompet</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('transaction.index') }}">
                <i class="fas fa-fw fa-edit"></i>
                <span>Data Transaksi Qurban</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('document.edit') }}">
                <i class="fas fa-fw fa-id-card"></i>
                <span>Kelengkapan Document</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('pengaturan-bank.edit') }}">
                <i class="fas fa-fw fa-cogs"></i>
                <span>Pengaturan Bank</span></a>
        </li>
    @else
    @endif
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
            aria-controls="collapsePages">
            <i class="fas fa-fw fa-user"></i>
            <span>Profile</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Profile:</h6>
                <a class="collapse-item" href="{{ route('profile.edit') }}">Profile</a>
                <a class="collapse-item" href="{{ route('user.password.edit') }}">Edit Password</a>
            </div>
        </div>
    </li>

    <hr class="sidebar-divider d-none d-md-block">

    <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-fw fa-sign-out-alt"></i>
            <span>Keluar</span>
        </a>
    </li>

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

resources/views/includes/admin/style.blade.php
<!-- Custom fonts for this template-->
<link href="{{ url('backend/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{ url('backend/css/sb-admin-2.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ url('backend/css/style.css') }}">
<link rel="stylesheet" href="{{ url('backend/vendor/datatables/dataTables.bootstrap4.min.css') }}">