routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('/program', 'MenuController@program')
    ->name('program');
Route::get('/faq', 'MenuController@faq')
    ->name('faq');
Route::get('/galeri', 'MenuController@galeri')
    ->name('galeri');
Route::get('/download', 'MenuController@download')
    ->name('download');

Route::get('/agent', 'HomeController@agent');

Route::get('/register/agen', 'Auth\RegisterController@showAgenRegisterForm')
    ->name('register.agen');

Route::post('/register/prosess', 'Auth\RegisterController@prosess')
    ->name('register.prosess');

Route::get('/detail/{slug}', 'DetailController@index')
    ->name('detail');

// user login
Route::post('/checkout/{id}', 'CheckoutController@process')
    ->name('checkout_process');
// ->middleware(['auth', 'verified']);

Route::get('/checkout/{id}', 'CheckoutController@index')
    ->name('checkout');
// ->middleware(['auth', 'verified']);

Route::post('/checkout/create/{detail_id}', 'CheckoutController@create')
    ->name('checkout-create');
// ->middleware(['auth', 'verified']);

Route::get('/checkout/remove/{detail_id}', 'CheckoutController@remove')
    ->name('checkout-remove');
// ->middleware(['auth', 'verified']);

Route::post('/send-wa', 'CheckoutController@sendWhatsapp');

Route::get('/checkout/confirm/{id}', 'CheckoutController@success')
    ->name('checkout-success');
// ->middleware(['auth', 'verified']);

Route::group(['middleware' => 'auth', 'verified'], function () {

    Route::get('/profile', 'ProfileController@edit')
        ->name('profile.edit')
        ->middleware(['auth', 'verified']);

    Route::patch('/profile', 'ProfileController@update')
        ->name('profile.update')->middleware(['auth', 'verified']);

    Route::get('/pengaturan-bank', 'PengaturanBankController@edit')
        ->name('pengaturan-bank.edit')->middleware(['auth', 'verified']);

    Route::patch('/pengaturan-bank', 'PengaturanBankController@update')
        ->name('pengaturan-bank.update')->middleware(['auth', 'verified']);

    Route::get('/document', 'DocumentController@edit')
        ->name('document.edit')->middleware(['auth', 'verified']);

    Route::patch('/document', 'DocumentController@update')
        ->name('document.update')->middleware(['auth', 'verified']);

    Route::get('password', 'PasswordController@edit')
        ->name('user.password.edit')->middleware(['auth', 'verified']);

    Route::patch('password', 'PasswordController@update')
        ->name('user.password.update')->middleware(['auth', 'verified']);

    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index')->middleware(['auth', 'verified']);
    Route::resource('transaction', 'TransactionController')->middleware(['auth', 'verified']);
    // Route::get('transaction', 'TransactionController@index')
    //     ->name('transaction.index')->middleware(['auth', 'verified']);
    Route::get('dompet', 'DompetController@index')
        ->name('dompet.index')->middleware(['auth', 'verified']);
});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

//agratek
Route::post('/agratek/callback', 'InvoiceController@agratekCallback');

// admin
Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('banks', 'BanksController');
        Route::resource('role', 'RoleController');
        Route::resource('product', 'ProductController');
        Route::resource('gallery', 'GalleryController');

        Route::resource(
            'addtransaksi',
            'AddtransaksiController',
            ['except' => [
                'show', 'update', 'index', 'destroy ',
                'edit'
            ]]
        );
    });

Auth::routes(['verify' => true]);

// midtrans
// Route::post('/midtrans/callback', 'MidtransController@notificationHandler');
Route::get('/invoice/{id}', 'InvoiceController@finishRedirect')
    ->name('invoice');
// Route::get('/midtrans/unfinish', 'MidtransController@unfinishRedirect');
// Route::get('/midtrans/error', 'MidtransController@errorRedirect');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\TransactionRequest;
use App\Transaction;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = Auth::user()->role_id;

        if ($user_id == 1) {

            $items = Transaction::with([
                'details', 'product', 'user', 'bank'
            ])->get();

            return view('pages.transaction.index', [
                'items' => $items
            ]);
        } elseif ($user_id == 2) {
            $items = Transaction::with([
                'details', 'product', 'user', 'bank'
            ])->where('users_id', '=', Auth::user()->id)
                ->get();
            return view('pages.transaction.index', [
                'items' => $items
            ]);
        } else {
            $items = Transaction::with([
                'details', 'product', 'user', 'bank'
            ])->where('users_id', '=', Auth::user()->id)
                ->get();
            return view('pages.transaction.index', [
                'items' => $items
            ]);
        }
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TransactionRequest $request)
    {
        $data = $request->all();

        Transaction::create($data);
        return redirect()->route('transaction.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Transaction::with([
            'details', 'product', 'user'
        ])->findOrFail($id);

        return view('pages.transaction.detail', [
            'item' => $item
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $item = Transaction::findOrFail($id);
            return view('pages.transaction.edit', [
                'item' => $item
            ]);
        } else {
            return abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TransactionRequest $request, $id)
    {
        dd($request->all());
        $data = $request->all();

        $item = Transaction::findOrFail($id);

        $item->update($data);

        return redirect()->route('transaction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $item = Transaction::findorFail($id);
            $item->delete();
            return redirect()->route('transaction.index');
        } else {
            return abort(404);
        }
    }
}

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Transaction;

class TransactionsController extends Controller
{
    public function index(Request $request)
    {
        return view('pages.transactions.index', [
            'transaction' => Transaction::count(),
            'transaction_pending' => Transaction::where('transaction_status', 'PENDING')->count(),
            'transaction_daftar' => Transaction::where('transaction_total')->count(),
        ]);
    }
}

resources/views/pages/transaction/detail.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container-fluid">
        <div class="row mt-12">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="col-xl-12 col-md-8 mb-5">
                        @if (session()->has('sukses'))
                            <div class="alert alert-info col-xl-12 alert-dismissible fade show" role="alert">
                                {{ session()->get('sukses') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                        <div class="card border-left-warning shadow h-100 py-2">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                                        <h1 class="h3 mb-0 text-gray-800">Detail Transaksi</h1>
                                    </div>
                                    <!-- Content Row -->
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Invoice</th>
                                            <td>{{ $item->invoice }}</td>
                                        </tr>
                                        <tr>
                                            <th width="25%">Pembeli</th>
                                            <td>{{ $item->name }}</td>
                                        </tr>
                                        <tr>
                                            <th>Tanggal</th>
                                            <td>{{ $item->created_at }}</td>
                                        </tr>
                                        <tr>
                                            <th>Bank</th>
                                            <td>{{ $item->bank->name }}</td>
                                        </tr>
                                        <tr>
                                            <th>Total Transaksi</th>
                                            <td><b><?php echo 'Rp. ' . number_format($item->total_seluruh, 0,
                                                    '.', '.'); ?></b></td>
                                        </tr>
                                        <tr>
                                            <th>Status Transaksi</th>
                                            <td>
                                                @if ($item->transaction_status == 'SUCCESS')
                                                    <b style="color:#d07c28;">LUNAS</b>
                                                @elseif($item->transaction_status != 'SUCCESS')
                                                    <b style="color:#d07c28;">BELUM LUNAS</b>
                                                @endif
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Alamat</th>
                                            <td>{{ $item->address }}</td>
                                        </tr>
                                        <tr>
                                            <th>Kota</th>
                                            <td>{{ $item->city }}</td>
                                        </tr>
                                        <tr>
                                            <th>Provinsi</th>
                                            <td>{{ $item->state }}</td>
                                        </tr>
                                        <tr>
                                            <th>Kode Post</th>
                                            <td>{{ $item->post_code }}</td>
                                        </tr>
                                        <tr>
                                            <th colspan="2" style="color:#d07c28;">Qurban</th>
                                        </tr>
                                        <tr>
                                            <th>{{ $item->product->title }}</th>
                                            <td>
                                                <table class="table table-bordered">
                                                    <tr>
                                                        <th>No</th>
                                                        <th>Nama</th>
                                                    </tr>
                                                    @php $no = 1; @endphp
                                                    @foreach ($item->details as $detail)
                                                        <tr>
                                                            <td>{{ $no++ }}</td>
                                                            <td>{{ $detail->username }}</td>
                                                        </tr>
                                                    @endforeach
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/transaction/dompet.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container-fluid">
        <div class="row mt-12">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="col-xl-12 col-md-8 mb-5">
                        @if (session()->has('sukses'))
                            <div class="alert alert-info col-xl-12 alert-dismissible fade show" role="alert">
                                {{ session()->get('sukses') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                        <div class="card border-left-warning shadow h-100 py-2">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                                        <h3 class="h3 mb-0 text-gray-800">Dompet</h3>
                                    </div>

                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Invoice</th>
                                                <th>Nama</th>
                                                <th>Telp</th>
                                                <th>Total</th>
                                                <th>Pembayaran</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @php $no = 1; @endphp
                                            @forelse($items as $item)
                                                <tr>
                                                    <td>{{ $no++ }}</td>
                                                    <td>{{ $item->invoice }}</td>
                                                    <td>{{ $item->user->username }}</td>
                                                    <td>{{ $item->nohp }}</td>
                                                    <td><?php echo 'Rp. ' . number_format($item->total_seluruh,
                                                        0, '.', '.'); ?>
                                                    </td>
                                                    <td>{{ $item->transaction_status }}</td>
                                                    <td>{{ $item->bank->name }}</td>
                                                    <td>
                                                        <a href="{{ route('transaction.show', $item->id) }}"
                                                            class="btn btn-primary">
                                                            <i class="fa fa-search-plus"></i>
                                                        </a>
                                                        @if (Auth::user()->role_id == 1)
                                                            <a href="{{ route('transaction.edit', $item->id) }}"
                                                                class="btn btn-info">
                                                                <i class="fa fa-pencil-alt"></i>
                                                            </a>
                                                            <form action="{{ route('transaction.destroy', $item->id) }}"
                                                                method="post" class="d-inline">
                                                                @csrf
                                                                @method('delete')
                                                                <button class="btn btn-danger">
                                                                    <i class="fa fa-trash"></i>
                                                                </button>
                                                            </form>
                                                        @else
                                                        @endif
                                                    </td>
                                                </tr>
                                            @empty
                                                <td colspan="7" class="text-center">
                                                    Data Kosong
                                                </td>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/transaction/edit.blade.php
@extends('layouts.admin')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Content Row -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row mt-12">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="col-xl-12 col-md-8 mb-5">
                        <div class="card border-left-warning shadow h-100 py-2">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="modal-body">
                                        <h3 class="h3 mb-4 text-gray-800">
                                            Ubah Transaksi {{ $item->title }}
                                        </h3>
                                        <hr>
                                        <form action="{{ route('transaction.update', $item->id) }}" method="post">
                                            @method('PUT')
                                            @csrf
                                            <div class="form-group">
                                                <label for="title">Status</label>
                                                <select name="transaction_status" required class="form-control">
                                                    <option value="{{ $item->transaction_status }}">Ubah Transaksi
                                                        ({{ $item->transaction_status }})
                                                    </option>
                                                    <option value="SUCCESS">Success</option>
                                                    <option value="IN_CART">In Cart</option>
                                                    <option value="PENDING">Pending</option>
                                                    <option value="CANCEL">Cancel</option>
                                                    <option value="FAILED">Failed</option>
                                                </select>
                                            </div>
                                            <button type="submit" class="btn admin-login btn-user btn-block admin-btn">
                                                Ubah
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/transaction/index.blade.php
@extends('layouts.admin')
@section('content')

    <div class="container-fluid">
        <div class="card shadow mb-4">
            @if (session()->has('sukses'))
                <div class="alert alert-info col-xl-12 alert-dismissible fade show" role="alert">
                    {{ session()->get('sukses') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="table-responsive">
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h3 class="h3 mb-0 text-gray-800">Transaksi</h3>
                        </div>
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Invoice</th>
                                    <th>Nama</th>
                                    <th>Telp</th>
                                    <th>Total</th>
                                    <th>Pembayaran</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $no = 1; @endphp
                                @forelse($items as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->invoice }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->nohp }}</td>
                                        <td><?php echo 'Rp. ' . number_format($item->total_seluruh, 0, '.',
                                            '.'); ?>
                                        </td>
                                        <td>
                                            @if ($item->transaction_status == 'SUCCESS')
                                                <b style="color:#d07c28;">LUNAS</b>
                                            @elseif($item->transaction_status != 'SUCCESS')
                                                <b style="color:#d07c28;">BELUM LUNAS</b>
                                            @endif
                                        </td>
                                        <td>{{ $item->bank->name }} ({{ $item->bank->rek }})</td>
                                        <td>
                                            <a href="{{ route('transaction.show', $item->id) }}" class="btn btn-primary">
                                                <i class="fa fa-search-plus"></i>
                                            </a>
                                            @if (Auth::user()->role_id == 1)
                                                <a href="{{ route('transaction.edit', $item->id) }}" class="btn btn-info">
                                                    <i class="fa fa-pencil-alt"></i>
                                                </a>
                                                <form action="{{ route('transaction.destroy', $item->id) }}" method="post"
                                                    class="d-inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            @else
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <td colspan="7" class="text-center">
                                        Data Kosong
                                    </td>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection